// This file is auto-generated by `wrangler types`.
// Do not edit manually — run `npx wrangler types` when wrangler.jsonc changes.

declare global {
	const env: {
		DB: D1Database;
		ASSETS: { fetch: (request: Request) => Promise<Response> };
		B2_API_URL: string;
		B2_BUCKET_NAME: string;
		VALCORNER_REDIRECT_URI: string;
		VALCORNER_SCOPE: string;
		VALCORNER_AUTHORIZE_URL: string;
		VALCORNER_TOKEN_URL: string;
		VALCORNER_USERINFO_URL: string;
		FRONTEND_URL: string;
	};
}

export {};
